"""Initial migration

Revision ID: 2e8e83f8318f
Revises: 
Create Date: 2025-11-24 15:16:03.707528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8e83f8318f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_files_conversation', 'files', type_='foreignkey')
    op.drop_column('files', 'conversation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_files_conversation', 'files', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
