"""initial clean schema

Revision ID: c0fbbd470863
Revises: 
Create Date: 2026-03-24 12:10:19.298030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fbbd470863'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_usage_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_usage_logs'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('model_source', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('storage_path', sa.String(length=2048), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('extension', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_kind', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('chunks_count', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_files_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_files_storage_key'))
    )
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.create_table('chat_file_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('attached_by_user_id', sa.UUID(), nullable=False),
    sa.Column('attached_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attached_by_user_id'], ['users.id'], name=op.f('fk_chat_file_links_attached_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['conversations.id'], name=op.f('fk_chat_file_links_chat_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_chat_file_links_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_file_links')),
    sa.UniqueConstraint('chat_id', 'file_id', name='uq_chat_file_links_chat_file')
    )
    op.create_index(op.f('ix_chat_file_links_chat_id'), 'chat_file_links', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_file_links_file_id'), 'chat_file_links', ['file_id'], unique=False)
    op.create_table('file_processing_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('artifact_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_provider', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('chunking_strategy', sa.String(length=128), nullable=True),
    sa.Column('retrieval_profile', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ingestion_progress', sa.JSON(), nullable=True),
    sa.Column('artifact_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_file_processing_profiles_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_processing_profiles'))
    )
    op.create_index(op.f('ix_file_processing_profiles_file_id'), 'file_processing_profiles', ['file_id'], unique=False)
    op.create_index('ix_file_processing_profiles_file_id_is_active', 'file_processing_profiles', ['file_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_file_processing_profiles_is_active'), 'file_processing_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_file_processing_profiles_status'), 'file_processing_profiles', ['status'], unique=False)
    op.create_index('uq_file_processing_profiles_active', 'file_processing_profiles', ['file_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generation_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_index('uq_file_processing_profiles_active', table_name='file_processing_profiles', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_file_processing_profiles_status'), table_name='file_processing_profiles')
    op.drop_index(op.f('ix_file_processing_profiles_is_active'), table_name='file_processing_profiles')
    op.drop_index('ix_file_processing_profiles_file_id_is_active', table_name='file_processing_profiles')
    op.drop_index(op.f('ix_file_processing_profiles_file_id'), table_name='file_processing_profiles')
    op.drop_table('file_processing_profiles')
    op.drop_index(op.f('ix_chat_file_links_file_id'), table_name='chat_file_links')
    op.drop_index(op.f('ix_chat_file_links_chat_id'), table_name='chat_file_links')
    op.drop_table('chat_file_links')
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_table('files')
    op.drop_table('conversations')
    op.drop_table('api_usage_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
